name: Docker Image CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code from the repository.
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --tag sarathjeeva/container-php-image:$(date +%s)
